addons:
  apt:
    update: true
    packages:
    - cmake
    - cppcheck
    - valgrind

stages:
  - codestyle
  - build
  - memcheck
  - test

language: cpp

env:
    - if: branch!=master
      - TARGET_DIR=${TRAVIS_BRANCH}
    - if: branch=master
      - TARGET_DIR=.

before_install:
    - chmod +x ./${TARGET_DIR}/memcheck.sh
    - sudo apt install libgtest-dev
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib
    - cd -

stages:
  - codestyle
  - build
  - memcheck
  - test

before_script:
  - cd ${TARGET_DIR}
  - cmake CMakeLists.txt
  - make

jobs:
  include:
    - stage: codestyle
      before_script: skip
      script: cppcheck --std=c++11 --enable=all -q --error-exitcode=1 .

    - stage: memcheck
      if: branch!=master
      script: ./memcheck.sh
    
    - stage: test
      script: ctest --output-on-failure    
      after_script: make clean
