addons:
  apt:
    update: true
    packages:
    - cmake
    - cppcheck
    - valgrind

stages:
  - codestyle
  - build
  - memcheck
  - test

language: cpp

env:
    - TARGET_DIR=${TRAVIS_BRANCH}
    - DEV=dev

before_install:
    - sudo apt install libgtest-dev
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib
    - cd -
    - ls

before_script:
  - cmake CMakeLists.txt
  - make

stages:
  - codestyle
  - build
  - memcheck
  - test

jobs:
  include:
    - stage: codestyle
      script: cppcheck --std=c++11 -q --enable=all --error-exitcode=1 .
    
    - stage: build
      script: cmake CMakeLists.txt && make

    - stage: memcheck
      env: DEV=dev
      script: valgrind --tool=memcheck --leak-check=full -q ./${TARGET_DIR}/app.exe -memcheck
    
    - stage: test
      script: ctest --output-on-failure    
      after_script: make clean

  exclude:
    - if: branch = master
      env: DEV=dev