addons:
  apt:
    update: true
    packages:
    - cmake
    - cppcheck
    - valgrind

stages:
  - codestyle
  - build
  - memcheck
  - test

language: cpp

env:
    - TARGET_DIR=${TRAVIS_BRANCH}

before_install:
    - sudo apt install libgtest-dev
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib
    - cd -
    - ls

stages:
  - codestyle
  - build
  - memcheck
  - test

before_script:
  - cmake CMakeLists.txt
  - make

jobs:
  include:
    - stage: codestyle
      before_script: skip
      script: cppcheck --std=c++11 --enable=all --error-exitcode=1 .

    - stage: memcheck
      if: branch!=master
      script: valgrind --tool=memcheck --leak-check=full -q ./${TARGET_DIR}/app.exe -memcheck
    
    - stage: test
      script: ctest --output-on-failure    
      after_script: make clean
